### ISSUE TITLE
Ready for Typo3 11.5

### ISSUE THREAD

**Issue by martin-git-kristensen** [invokablegmbh/jar_columnrow#1]
Even if it is proclamed - you can´t install it on typo3 11.5 because flux is not ready for typo3 11.5
Is there at change for it will work on typo3 11.5 soon?

**Comment by invokablegmbh** [comment]
Hello martin-git-kristensen,

unfortunately not, we also wait for flux to be runnable under TYPO3 11.5. The actual dev version of flux is already marked for TYPO3 11.5 - so hopefully it would be a matter of short time.

**Comment by martin-git-kristensen** [comment]
Now flux i ready for typo3 11 but I still get this error in my backend after installing jar_columnrow, jar_utilities and flex
1/1) Error

Call to a member function getAttribute() on null
in /var/www/html/public/typo3conf/ext/jar_utilities/Classes/Utilities/BackendUtility.php line 89

**Comment by martin-git-kristensen** [comment]
When outcomment the lines 89 to 91 in BackendUtility.php it seems that the extension works on my typo3 11.5.16 and php 7.4.24

if($GLOBALS['TYPO3_REQUEST']->getAttribute('route') && strpos($GLOBALS['TYPO3_REQUEST']->getAttribute('route')->getOption('moduleName'), 'file_') !==  false) {
return null;
		}

**Comment by martin-git-kristensen** [comment]
I´ve got a lot of error frontend when I upgrade my php to 8.0.11

**Comment by invokablegmbh** [comment]
Please test the last version, we removed the PHP 8 warnings in jar_utilities and jar_columnrow.

**Comment by invokablegmbh** [comment]
Closed with https://github.com/invokablegmbh/jar-utilities/issues/1
